"""remove_very_busy_status_and_queue_count

Revision ID: 40f791c73a0e
Revises: 5c63866ef1dc
Create Date: 2025-11-30 17:31:04.870995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40f791c73a0e'
down_revision: Union[str, None] = '5c63866ef1dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Convert all very_busy statuses to busy before removing the enum value
    op.execute("UPDATE business_status SET status = 'busy' WHERE status = 'very_busy'")
    op.execute("UPDATE status_history SET status = 'busy' WHERE status = 'very_busy'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_status', 'current_queue_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_status', sa.Column('current_queue_count', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
